### ISSUE TITLE
Create Table: new icon

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-prototypes#217] opened 2020-09-21 11:43 UTC
Improve icon for Create Table.

**Comment by PrimozGodec** [comment] 2021-02-19 13:44
The new issue is already open in educational https://github.com/biolab/orange3-educational/issues/107. Close this one when https://github.com/biolab/orange3-educational/pull/106 is getting merged.

**Comment by janezd** [comment] 2021-02-19 14:19
I think it can be closed now if the issue is already moved there.

**Closed** 2021-02-19 14:19 UTC
